title: Amutheezan's Blog
tagline: Get the solutions customized for you

author:
  name: Amutheezan Sivagnanam
  url: https://twitter.com/amux93

twitter:
  username: amux93

defaults:
  - scope:
      path: ""      
      type: "posts"
    values:
      author: "Amutheezan Sivagnanam"
      image: "display_picture.jpeg"
  - scope:
      path: ""      
      type: "pages"
    values:
      author: "Amutheezan Sivagnanam"
      image: "display_picture.jpeg"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

remote_theme: zivong/jekyll-theme-hydure

paginate: 10

tags_path: /tags/
categories_path: /categories/
